version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:12.0.0
    steps:
      - checkout
      - run:
          name: Install npm deps
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: |
            npm run test
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys
      - run:
          name: Deploy via SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "./deploy.sh"
workflows:
  build_test:
    jobs:
      - run_tests
  deploy:
    jobs:
      - deploy
          requires:
            - run_tests
          filters:
            branches:
              only: main
