version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:12.0.0
    steps:
      - checkout
      - run:
        name: Install npm deps
        command: |
          npm install --save
      - run:
        name: Run Unit Tests
        command: |
          npm run test
workflows:
  build_test:
    jobs:
      - run_tests
